(setf (current-problem)
	(create-problem
		(name p1)
			(objects
				(h2 h3 h1 h6 h4 h5 HOUSE)
				(w3 CONSTRUCTION-WORKER)
				(w4 w1 FIREMAN)
				(w2 TEAMSTER)
				(m11 m13 m4 m1 m8 CONCRETE)
				(m12 m5 m2 m9 WOOD)
				(m7 m14 BRICK)
				(m10 m6 m3 m15 SHINGLE)
			)
			(state
				(and
					(has-foundation h2)
					(has-foundation h1)
					(has-brick-walls h1)
					(has-foundation h4)
					(has-wood-walls h4)
					(has-foundation h3)
					(has-brick-walls h3)
					(has-roof h3)
					(has-roof h5)
					(has-wood-walls h5)
					(has-foundation h5)
					(at m11 h4)
					(unused m11)
					(at m10 h2)
					(unused m10)
					(at m12 h6)
					(unused m12)
					(at m13 h3)
					(unused m13)
					(at m5 hq)
					(unused m5)
					(at m4 h5)
					(unused m4)
					(at m7 h5)
					(unused m7)
					(at m6 hq)
					(unused m6)
					(at m1 hq)
					(unused m1)
					(at m14 h2)
					(unused m14)
					(at m3 h4)
					(unused m3)
					(at m2 h5)
					(unused m2)
					(at m15 h6)
					(unused m15)
					(at m9 h2)
					(unused m9)
					(at m8 h4)
					(unused m8)
					(at w4 h3)
					(at w3 h4)
					(at w2 h1)
					(at w1 h2)
				)
			)
			(goal
				(and
					(complete h3)
					(complete h6)
					(has-brick-walls h2)
					(complete h4)
					(has-wood-walls h5)
					(complete h1)
				)
			)
	)
)