(setf (current-problem)
	(create-problem
		(name p2)
			(objects
				(h2 h3 h1 h6 h4 h5 HOUSE)
				(w3 CONSTRUCTION-WORKER)
				(w4 w1 FIREMAN)
				(w2 TEAMSTER)
				(m5 m1 m8 CONCRETE)
				(m6 m2 m9 WOOD)
				(m4 m7 m3 SHINGLE)
			)
			(state
				(and
					(has-foundation h2)
					(has-brick-walls h2)
					(has-foundation h5)
					(at m5 h6)
					(unused m5)
					(at m4 h5)
					(unused m4)
					(at m7 hq)
					(unused m7)
					(at m6 h5)
					(unused m6)
					(at m1 h2)
					(unused m1)
					(at m3 h3)
					(unused m3)
					(at m2 h3)
					(unused m2)
					(at m9 h2)
					(unused m9)
					(at m8 h2)
					(unused m8)
					(at w4 hq)
					(at w3 h3)
					(at w2 h4)
					(at w1 h3)
				)
			)
			(goal
				(and
					(has-foundation h3)
					(complete h5)
					(has-roof h2)
					(has-foundation h1)
					(complete h6)
					(has-wood-walls h4)
				)
			)
	)
)