(setf (current-problem)
	(create-problem
		(name p3)
			(objects
				(h2 h3 h1 h6 h7 h4 h5 HOUSE)
				(w3 CONSTRUCTION-WORKER)
				(w1 FIREMAN)
				(w4 w2 TEAMSTER)
				(m5 m7 m2 CONCRETE)
				(m6 m3 WOOD)
				(m1 m8 BRICK)
				(m4 m9 SHINGLE)
			)
			(state
				(and
					(has-foundation h5)
					(at m5 h7)
					(unused m5)
					(at m4 h4)
					(unused m4)
					(at m7 h3)
					(unused m7)
					(at m6 hq)
					(unused m6)
					(at m1 hq)
					(unused m1)
					(at m3 h7)
					(unused m3)
					(at m2 h4)
					(unused m2)
					(at m9 h1)
					(unused m9)
					(at m8 h2)
					(unused m8)
					(at w4 h6)
					(at w3 h3)
					(at w2 h7)
					(at w1 h3)
				)
			)
			(goal
				(and
					(has-brick-walls h5)
					(complete h3)
					(has-wood-walls h2)
					(complete h1)
				)
			)
	)
)