(setf (current-problem)
	(create-problem
		(name p5)
			(objects
				(h2 h3 h1 h6 h4 h5 HOUSE)
				(w4 w3 CONSTRUCTION-WORKER)
				(w1 FIREMAN)
				(w2 TEAMSTER)
				(m3 m8 CONCRETE)
				(m4 m6 m9 WOOD)
				(m1 BRICK)
				(m10 m5 m7 m2 SHINGLE)
			)
			(state
				(and
					(has-foundation h2)
					(has-roof h2)
					(has-wood-walls h2)
					(complete h2)
					(has-foundation h3)
					(has-foundation h4)
					(has-wood-walls h4)
					(has-foundation h5)
					(at m10 h5)
					(unused m10)
					(at m5 hq)
					(unused m5)
					(at m4 h4)
					(unused m4)
					(at m7 h5)
					(unused m7)
					(at m6 h2)
					(unused m6)
					(at m1 h5)
					(unused m1)
					(at m3 h5)
					(unused m3)
					(at m2 h4)
					(unused m2)
					(at m9 h5)
					(unused m9)
					(at m8 h5)
					(unused m8)
					(at w4 h1)
					(at w3 h4)
					(at w2 h3)
					(at w1 h6)
				)
			)
			(goal
				(and
					(complete h3)
					(complete h1)
					(has-wood-walls h5)
					(complete h4)
					(has-roof h2)
					(complete h6)
				)
			)
	)
)